### ISSUE TITLE
Not working with latest FD (5.3.4.385)

### ISSUE THREAD

**Issue by andrew-git** [SlavaRa/fdplugin-postfix-code-completion#82]
When type "." after variable got exception

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at PostfixCodeCompletion.Helpers.ASGeneratorReflector.GetStatementReturnType(ScintillaControl sci, String line, Int32 positionFromLine)
>    at PostfixCodeCompletion.Helpers.CompleteHelper.GetCurrentExpressionType()
>    at PostfixCodeCompletion.Completion.PCCComplete.UpdateCompletionList(IList`1 options)
>    at PostfixCodeCompletion.Completion.PCCASComplete.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
>    at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

**Comment by SlavaRa** [comment]
https://github.com/fdorg/flashdevelop/commit/6c1533ceac
```
Метод не найден: "Boolean PluginCore.Utilities.SemVer.IsOlderThan(PluginCore.Utilities.SemVer)".

   в PostfixCodeCompletion.Completion.PCCHaxeComplete.OnHaxeCompletionModeChanged()
   в PostfixCodeCompletion.Completion.PCCHaxeComplete.Start()
   в PostfixCodeCompletion.Completion.Complete.Start()
   в PostfixCodeCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   в PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e) в D:\work\flashdevelop\PluginCore\PluginCore\Managers\EventManager.cs:строка 121
```
